plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.20'
}

version = "${mcversion}-${mod_version}-${tag_lanzador}"
group = "${author}.${modid}"
base {
    archivesName = "${mod_named}"
}

// Mojang ships Java 21 to end users in 1.20.5+, so your mod should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')
//minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
        systemProperty 'neoforge.enabledGameTestNamespaces', project.modid
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.modid
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.modid
    }
    clientData {
       arguments.addAll '--mod', project.modid, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

repositories {
       maven {
        url 'https://maven.blakesmods.com'
    }
     maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/" //JEI
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    //jei
    compileOnly "mezz.jei:jei-${mcversion}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${mcversion}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${mcversion}-neoforge:${jei_version}"
     
    // mystical agriculture
    implementation "com.blakebr0.cucumber:Cucumber:${mcversion}-${cucumber_version}"
    implementation "com.blakebr0.mysticalagriculture:MysticalAgriculture:${mcversion}-${mystical_version}"
}
tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            mcversion              : mcversion,
            mod_version            : mod_version,
            modid                  : modid,
            author                 : author,
            mod_named              : mod_named,
            mod_name               : mod_name,
            tag_lanzador           : tag_lanzador,
            description            : description,
            mod_license            : mod_license,
            issue_tracker          : issue_tracker,
            neo_version             : neo_version,
            loader_version         : loader_version,
            mystical_version       : mystical_version,
            cucumber_version       : cucumber_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    options.getRelease().set(25)
}