org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

author=NadienDev
modid=mysticalagricultecompats
mod_named=Mystical Agriculture Compats
mod_name=Mystical_Agriculture_Compats
description= Mystical Agriculture Reprocessors Compats.
mod_license=MIT
mod_group_id=nadiendev.ae2usefulutilities
mod_version=1.0.0
tag_lanzador=NeoForge
issue_tracker=

# Minecraft and NeoForge versions
mcversion=1.21.1
neo_version=21.1.240
loader_version=[4,)

# NeoForge Parchment
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

## Dependencies
mystical_version=8.0.27
cucumber_version=8.0.16
jei_version=19.42.0.385